In [53]:
import numpy
import random
import copy

In [54]:
value = numpy.zeros( (4,4) , "float" )      # State-Value Matrix
gamma = 0.9             # Dis-Counting Factor
threshold = .3          #   THRESHOLD FOR STOPPING VALUE ITERATION

In [55]:
def Immediate_reward(i1,j1) :
    if (i1==0 and j1==0 ) or (i1==3 and j1==3) :
        return 0 
    else :
        return -1 

In [56]:
def State_Value(value,i,j,i1,j1) :
    if (i1<0 or i1>3 or j1<0 or j1>3) :
        return value[i][j]
    else :
        return value[i1][j1]

In [57]:
def update(value,i,j) :
    reward_list= []
    action_list = []
    for i1,j1,A in [ (i-1,j,1) , (i+1,j,2) , (i,j-1,3) , (i,j+1,4) ] :
        reward = Immediate_reward(i1,j1) + gamma*State_Value(value,i,j,i1,j1)
        reward_list.append( reward )
        action_list.append(A)
    maximum = max(reward_list) #   Finding maximum reward
    maximum_list = []          # Multiple actions could have Same Maximum rewards 
    for i in range(4) :
        if maximum == reward_list[i] :
            maximum_list.append(i)
    index = random.choice(maximum_list)       # randomly selecting index to take action(optimal)
    return [maximum, action_list[index] ]

In [58]:
def Value_Iteration(value,max_iter,threshold) :
    old_value = copy.deepcopy(value)
    action = numpy.zeros( (4,4) , "int" )
    diff_list = []
    for iter in range(max_iter) :
        print("\n\n\nITERATION NUMBER\t",iter+1)
        for i in range(4) :
            for j in range(4) :
                if not( ( i==0 and j==0 ) or (i==3 and j==3) ) : 
                     ANS = update(value,i,j)
                     value[i][j] = ANS[0]
                     action[i][j] = ANS[1]
                     diff_list.append( old_value[i][j] - value[i][j] )
        print("-----STATE VALUE MATRIX")
        print( value )
        print("-----STATE-ACTION MATRIX")
        print(action)
        diff_maximum = max(diff_list)
        print("MAX Difference ",diff_maximum)
        if (diff_maximum<=threshold) :
            print("Terminating because threshod is achived")
            break 
    return action

Below set max_iter 

After completing max_iter number  of iterations Iteration stops

In [59]:
max_iter = 20

In [60]:
state_action = Value_Iteration(value,max_iter,threshold)




ITERATION NUMBER	 1
-----STATE VALUE MATRIX
[[ 0.  0. -1. -1.]
 [ 0. -1. -1. -1.]
 [-1. -1. -1.  0.]
 [-1. -1.  0.  0.]]
-----STATE-ACTION MATRIX
[[0 3 1 4]
 [1 1 4 4]
 [2 4 2 2]
 [4 4 4 0]]
MAX Difference  1.0



ITERATION NUMBER	 2
-----STATE VALUE MATRIX
[[ 0.   0.  -1.  -1.9]
 [ 0.  -1.  -1.9 -1. ]
 [-1.  -1.9 -1.   0. ]
 [-1.9 -1.   0.   0. ]]
-----STATE-ACTION MATRIX
[[0 3 3 2]
 [1 3 1 2]
 [1 3 2 2]
 [4 4 4 0]]
MAX Difference  1.9



ITERATION NUMBER	 3
-----STATE VALUE MATRIX
[[ 0.   0.  -1.  -1.9]
 [ 0.  -1.  -1.9 -1. ]
 [-1.  -1.9 -1.   0. ]
 [-1.9 -1.   0.   0. ]]
-----STATE-ACTION MATRIX
[[0 3 3 3]
 [1 1 4 2]
 [1 3 4 2]
 [4 4 4 0]]
MAX Difference  1.9



ITERATION NUMBER	 4
-----STATE VALUE MATRIX
[[ 0.   0.  -1.  -1.9]
 [ 0.  -1.  -1.9 -1. ]
 [-1.  -1.9 -1.   0. ]
 [-1.9 -1.   0.   0. ]]
-----STATE-ACTION MATRIX
[[0 3 3 3]
 [1 1 2 2]
 [1 2 2 2]
 [1 4 4 0]]
MAX Difference  1.9



ITERATION NUMBER	 5
-----STATE VALUE MATRIX
[[ 0.   0.  -1.  -1.9]
 [ 0.  -1.  -1.9 -1. ]
 [-

In [61]:
print("Final STATE-VALUE")
print(value)

Final STATE-VALUE
[[ 0.   0.  -1.  -1.9]
 [ 0.  -1.  -1.9 -1. ]
 [-1.  -1.9 -1.   0. ]
 [-1.9 -1.   0.   0. ]]


1==UP , 2==DOWN , 3==LEFT , 4==RIGTH

In [63]:
print("Final STATE-ACTION MATRIX")
print(state_action)

Final STATE-ACTION MATRIX
[[0 3 3 3]
 [1 3 2 2]
 [1 1 2 2]
 [1 4 4 0]]
